-- Generated by scripts/ops/build-prohibited-triggers.js from src/prohibited.js — do not edit by hand.
-- Blocks listings matching the prohibited-content blocklist at the database level.
DROP TRIGGER IF EXISTS block_prohibited_sites_insert;
-- statement-break
CREATE TRIGGER block_prohibited_sites_insert BEFORE INSERT ON sites
  WHEN instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinder porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childlover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'boylover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'boy lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'girllover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teenmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'junior idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'junioridol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jr idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'prepubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-pubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'little girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'little boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minor sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'sex with minor') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ninfet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedofil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'menor de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'menores de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minderjahrig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minderjährig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ロリ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ショタ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼女') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼児') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '小学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '中学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '児童') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ジュニアアイドル') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '未成年') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '萝莉') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼齿') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'малолет') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'лолит') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'педофил') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'детское порно') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_sites_update;
-- statement-break
CREATE TRIGGER block_prohibited_sites_update BEFORE UPDATE OF url, data_json ON sites
  WHEN instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinder porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childlover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'boylover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'boy lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'girllover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teenmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'junior idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'junioridol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jr idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'prepubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-pubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'little girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'little boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minor sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'sex with minor') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ninfet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedofil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'menor de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'menores de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minderjahrig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'minderjährig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ロリ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ショタ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼女') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼児') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '小学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '中学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '児童') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ジュニアアイドル') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '未成年') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '萝莉') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), '幼齿') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'малолет') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'лолит') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'педофил') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'детское порно') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_queue_insert;
-- statement-break
CREATE TRIGGER block_prohibited_queue_insert BEFORE INSERT ON queue
  WHEN instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinder porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childlover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'boylover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'boy lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'girllover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teenmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'junior idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'junioridol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jr idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'prepubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-pubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'little girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'little boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minor sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'sex with minor') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ninfet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedofil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'menor de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'menores de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minderjahrig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minderjährig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ロリ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ショタ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼女') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼児') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '小学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '中学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '児童') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ジュニアアイドル') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '未成年') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '萝莉') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼齿') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'малолет') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'лолит') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'педофил') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'детское порно') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_queue_update;
-- statement-break
CREATE TRIGGER block_prohibited_queue_update BEFORE UPDATE OF url, name ON queue
  WHEN instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinder porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childlover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'boylover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'boy lover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'girllover') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-model') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teenmodel') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'junior idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'junioridol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jr idol') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'prepubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-pubescent') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'little girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'little boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young girl') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young boy') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minor sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'sex with minor') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ninfet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedofil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'menor de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'menores de edad') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minderjahrig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'minderjährig') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ロリ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ショタ') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼女') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼児') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '小学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '中学生') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '児童') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ジュニアアイドル') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '未成年') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '萝莉') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), '幼齿') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'малолет') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'лолит') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'педофил') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'детское порно') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
