-- Generated by scripts/ops/build-prohibited-triggers.js from src/prohibited.js — do not edit by hand.
-- Blocks listings matching the prohibited-content blocklist at the database level.
DROP TRIGGER IF EXISTS block_prohibited_sites_insert;
-- statement-break
CREATE TRIGGER block_prohibited_sites_insert BEFORE INSERT ON sites
  WHEN instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinder porn') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_sites_update;
-- statement-break
CREATE TRIGGER block_prohibited_sites_update BEFORE UPDATE OF url, data_json ON sites
  WHEN instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(json_extract(NEW.data_json, '$.name'), '') || ' ' || COALESCE(json_extract(NEW.data_json, '$.description'), '')), 'kinder porn') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_queue_insert;
-- statement-break
CREATE TRIGGER block_prohibited_queue_insert BEFORE INSERT ON queue
  WHEN instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinder porn') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
DROP TRIGGER IF EXISTS block_prohibited_queue_update;
-- statement-break
CREATE TRIGGER block_prohibited_queue_update BEFORE UPDATE OF url, name ON queue
  WHEN instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jailbait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jail-bait') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbcam') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jbteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'jb-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'loli') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'shota') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lolita') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'underage') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'under-age') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'preteen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pre-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pthc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'childporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kiddie') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'toddler') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'schoolgirl-porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'paedophil') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'pedobear') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'child sex') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kids porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kid porn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudism') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nudist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'naturist') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'teen-young') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'young-teen') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candydoll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy-doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'candy doll') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'nymphet') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-models') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'lsmodels') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ls-island') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'hussyfan') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'ptsc') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'qqaazz') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinderporn') > 0
    OR instr(lower(NEW.url || ' ' || COALESCE(NEW.name, '')), 'kinder porn') > 0
BEGIN
  SELECT RAISE(IGNORE);
END;
-- statement-break
